# .github/workflows/ci.yml
name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
      - name: Run tests (with audit reporter)
        run: |
          mkdir -p artifacts
          pytest -q --audit-report-dir artifacts
      - name: Upload audit reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-audit-reports
          path: artifacts/*
